spring:
  datasource:
    url: jdbc:h2:mem:todo-db
    username: sa
    password: sa
    driverClassName: org.h2.Driver
  h2:
    console:
      enabled: true
  jpa:
    hibernate:
      ddl-auto: update
    database-platform: org.hibernate.dialect.H2Dialect

server:
  port: 3000
  servlet:
    context-path: "/api"